### PR TITLE
add support for prettier and editorconfig

### PR DESCRIPTION
**Pull request by fimblo**
### prettier
Applies style upon save in editor, and a check can be run in CI using `npm run prettier`. Autofix can be run in CI using `npm run prettier:fix`. 

In more detail:
> Prettier scans your files for style issues and automatically reformats your code to ensure consistent rules are being followed for indentation, spacing, semicolons, single quotes vs double quotes, etc

### editorconfig
Applies style (whitespace, wordwrap, etc) while writing the code in the editor. This config is also used by prettier.

### CODE REVIEW

**Comment by fimblo** [comment]
Oh and I guess editorconfig and prettier need to be added or enabled in your editors. Since it was easy to do for vscode as well as emacs, I'm guessing it should be simple in other editors.

Why I'm proposing this?
Because collaboration should be easier if we adapt to a common standard which is enforced by our editors.

**Comment by hkniberg** [comment]
Nice! This will make the code more consistent and easier to read. Will test how it works with Webstorm.

**Review by hkniberg — APPROVED** [review]

**Comment by hkniberg** [comment]
You set it as draft, does that mean you want to do more before merging this? Would be nice to get it merged pretty quickly before we start working with other stuff, to avoid merge conflicts.

**Comment by fimblo** [comment]
Oops, I made it a draft since I was at the time unsure how much more I wanted to do balanced with how tired I was. Then promptly forgot about it. sorry about that.

**Pull request merged**
